### ISSUE TITLE
script crashes at records with "encType":0 items

### ISSUE THREAD

**Issue by fhanzlik** [Unode/firefox_decrypt#1]
Hi Renato, my logins.json contains several records with '"encType":0' items (and corresponding "encryptedPassword": item is plaintext value). It seems as 'firefox_decrypt.py' ignore encType value and try decode this value and then crashes:
```
Traceback (most recent call last):
  File "/home/hanzlik/firefox_decrypt.py", line 250, in <module>
    main()
  File "/home/hanzlik/firefox_decrypt.py", line 237, in main
    out = decrypt_passwords(profile, password)
  File "/home/hanzlik/firefox_decrypt.py", line 147, in decrypt_passwords
    passwd.data = cast(c_char_p(b64decode(passw)), c_void_p)
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```
Line 147 is: 'passwd.data = cast(c_char_p(b64decode(passw)), c_void_p)'

**Comment by Unode** [comment]
Hi fhanzlik,

I've never seen `encType:0` which is why I've never implemented it. That is unless your entire keystore is not encrypted in which case this whole script is rather pointless :) .

In any case, I've implemented a workaround and it should no longer crash.
If it still does, please provide an anonymized and stripped `logins.json` file.
