### ISSUE TITLE
Extracting Passwords from Firefox Nightly on Android

### ISSUE THREAD

**Issue by krxdow** [unode/firefox_decrypt#109]
I am reaching out to you regarding a feature request that I would like to submit. Currently, I am looking for a way to extract passwords from Firefox Nightly on Android. I understand that your team primarily focuses on the desktop version, but I was wondering if there are any leads or suggestions for accomplishing this task on the mobile version.

On my Android mobile version, I have passwords stored that I access individually via a PIN code. However, I would like to be able to extract them in bulk, similar to the functionality available on the desktop version.

I would appreciate it if you could provide me with any advice or guidance on how to perform this operation on the Android version of Firefox Nightly.

Thank you in advance for your attention and assistance.

Best regards,

**Comment by unode** [comment]
Hi @krxdow,

Unfortunately due to Android's sandbox security model I doubt that a tool like this project can be created. If you have a rooted phone it may be possible but I don't have experience.

One possibility you could explore is to use Firefox Sync to transfer the passwords over to a desktop and then you should be able to use firefox-decrypt.

**Comment by krxdow** [comment]
Thank you for replying
And for the questions given
