### ISSUE TITLE
Prompt the user and download nss3.dll from Mozilla if not found or not compatible

### ISSUE THREAD

**Issue by beppe9000** [unode/firefox_decrypt#41]
I put nss3.dll in the script folder and run it from a CMD shell with the script in the working directory.

![image](https://user-images.githubusercontent.com/6625123/46828605-ddd2ba00-cd9b-11e8-88fe-4af5eb2393cb.png)

```
2018-10-11 21:20:33,456 - ERROR - Problems opening 'nss3.dll' required for password decryption
2018-10-11 21:20:33,456 - ERROR - Error was [WinError 126] Unable to find the specified module.
```

Ps. Can't the script just download the dll from the internet if not found?

**Comment by unode** [comment]
The reason why you are seeing that error is possibly related to #8 . You didn't provide any versions on either Python or Firefox (or where you got `nss3.dll` from), so I can't tell for sure.

Downloading `nss3.dll` from the internet is a possibility but this isn't supported, in part because there are many different `nss3.dll` files to pick from. I'd be open to a pull request implementing this behavior if you can find a reliable source for the file. Regardless, the recommended approach for Windows is to download and install Firefox.

**Comment by beppe9000** [comment]
Password files from cyberfox (a firefox fork) on x64 windows with x64 Python 3.7.0 and `nss3.dll` from x64 cyberfox. I also tried to add the cyberfox path to the find_nss function but it did not load.

Regarding a reliable source for nss have a look [here](https://ftp.mozilla.org/pub/security/nss/releases/).

**Comment by unode** [comment]
I'm not familiar with cyberfox.
I'd assume it should implement the same interface but clearly the `nss3.dll` included isn't binary compatible or is missing some additional dependency. I wonder if their optimizations are the reason... If you can test an official Firefox release this will be useful, otherwise I'm afraid I can't help there.

Thanks for the NSS release link. Most folders there only contain source code but a few include compiled bundles. This feature isn't something I'm planning to implement but a pull request is always welcome.

**Comment by vladtepesch** [comment]
please have a look at https://github.com/christophetd/firepwned/issues/13

if 32bit and 64bit firefos is installed than 64bit python choses the wrong dll.
Only the directories that match the current pythons bittage should be added.

there is a patch in the issue that can be easily adapted

**Comment by unode** [comment]
@vladtepesch I've included your suggestion but the patch doesn't actually address the underlying issue. The lib may still be of the wrong type.

https://stackoverflow.com/a/1351790 would be a better solution where the code actually tests if the library is compatible or not. I can't test this myself though as I don't run Windows and we don't yet have Windows tests, but a pull request is welcome.

**Comment by unode** [comment]
NSS no longer provides binary releases so the initial goal of this issue is no longer within reach.
We now also do a bit better at trying loading many of the common paths where `nss3.dll` would be found.

If you are still interested in pursuing this feel free to reopen.

**Comment by beppe9000** [comment]
alrighty, I think being smart with paths will do
