### ISSUE TITLE
How to import passwords

### ISSUE THREAD

**Issue by CoSoCo** [unode/firefox_decrypt#47]
**Can you clarify...**
Is there a program, which is able to import the exported passwords again, like addon "Password Exporter" does on old Mozilla versions?
If not, could you provide such program in future?

**Comment by unode** [comment]
Importing has never been a goal of this project.
It requires writing into the password store which opens up the possibility for data corruption or the creation of malformed data. Two things I don't want to get into.
In fact there's #40 which was likely caused by such kind of tool. 

I'm not aware of projects that do this, (never had the need myself so never looked for it), but I can see the use-case.
Unfortunately, at the moment I don't see this becoming part of firefox_decrypt which I want to keep strictly read-only.

A sister project perhaps... but not anytime soon.

**Comment by kastixx** [comment]
@unode Actually, I've nearly completed adding password import feature. If I made a PR, could it by any chance be merged or importing is totally out of the question here?

**Comment by CoSoCo** [comment]
> Actually, I've nearly completed adding password import feature. If I made a PR, could it by any chance be merged ...?

I would really appreciate that approach.

**Comment by kastixx** [comment]
@CoSoCo here's a draft: #56 

Meanwhile you may clone the fork https://github.com/kastixx/firefox_decrypt and try `mutate-current` branch. Warning - for now it works for me and passes unit tests, but nothing more, so please make backups!
